apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: 
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 
    targetRevision: 
  sources: []
  project: 
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
